[package]
name = "dmtri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "^1.4"
pbjson = "^0.5"
pbjson-types = "^0.5"
prost = "^0.12"
serde = "^1.0"
tonic = "^0.11"

[features]
default = []
## @@protoc_insertion_point(features)
