[package]
name = "dmtri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "^1.4"
futures-core = "0.3.30"
pbjson = "^0.7"
pbjson-types = "^0.7"
prost = "^0.13"
prost-types = "^0.13"
serde = "^1.0"
tonic = { version = "0.12.3", default-features = false, features = ["codegen", "prost"] }

[features]
default = []
## @@protoc_insertion_point(features)
